# Generated by Django 5.1.4 on 2025-01-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_coin_coinhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='spend_coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
