# Generated by Django 5.1.4 on 2025-01-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_lesson_document_alter_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(default=3, upload_to='lesson_videos/'),
            preserve_default=False,
        ),
    ]
